# NOTE: contains intentional security test patterns for SAST/SCA/IaC scanning.
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template for an application

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-app-bucket-12345
      # Removed AccessControl: PublicRead to address security vulnerability
      # The default ACL (private) will be used, which is more secure
      # Added cross-region replication configuration for improved data durability and availability
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Destination:
              Bucket: !Sub 'arn:aws:s3:::${AWS::StackName}-replica'
              Region: us-west-2  # Replication to a different region
            Status: Enabled
            Priority: 1
            DeleteMarkerReplication:
              Status: Enabled

  # IAM role for S3 replication
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource: !GetAtt AppBucket.Arn
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource: !Sub '${AppBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-replica/*'

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppFullPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'                       # Issue 2: wildcard action
                Resource: '*'                     # Issue 3: wildcard resource

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0                     # Issue 4: SSH open to the world